name: Code review

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches:
      - main
jobs:
  KtLint:
    uses: ./.github/workflows/reusable_unit_tests.yml
